# Generated by Django 4.1.7 on 2023-03-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extraPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, choices=[('LT', 'LukasT'), ('LL', 'LukasL'), ('J', 'Jojo'), ('M', 'Marc'), ('A', 'Aaron')], default='', max_length=30)),
                ('second', models.CharField(blank=True, choices=[('LT', 'LukasT'), ('LL', 'LukasL'), ('J', 'Jojo'), ('M', 'Marc'), ('A', 'Aaron')], default='', max_length=30)),
                ('third', models.CharField(blank=True, choices=[('LT', 'LukasT'), ('LL', 'LukasL'), ('J', 'Jojo'), ('M', 'Marc'), ('A', 'Aaron')], default='', max_length=30)),
                ('fourth', models.CharField(blank=True, choices=[('LT', 'LukasT'), ('LL', 'LukasL'), ('J', 'Jojo'), ('M', 'Marc'), ('A', 'Aaron')], default='', max_length=30)),
                ('fith', models.CharField(blank=True, choices=[('LT', 'LukasT'), ('LL', 'LukasL'), ('J', 'Jojo'), ('M', 'Marc'), ('A', 'Aaron')], default='', max_length=30)),
            ],
        ),
    ]
