# Generated by Django 4.2.4 on 2023-08-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnier', '0010_alter_results_deca_alter_results_discm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='hundredM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='100m Männer'),
        ),
    ]
