# Generated by Django 4.2.4 on 2023-08-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnier', '0011_alter_spieler_hundredm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='deca',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Zehnkampf'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='discM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Diskuswurf Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='discW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Diskuswurf Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='eightM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='800m Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='eightW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='800m Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fifteenM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='1500m Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fifteenW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='1500m Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fiveKM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='5km Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fiveKW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='5km Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fourHM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='400m Hürden Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fourHW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='400m Hürden Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fourM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='400m Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fourW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='400m Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fourxfourM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='4x400m Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fourxfourW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='4x400m Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fourxoneM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='4x100m Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='fourxoneW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='4x100m Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='hammerM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Hammerwurf Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='hammerW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Hammerwurf Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='hepta',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Siebenkampf'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='highM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Hochsprung Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='highW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Hochsprung Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='hundredW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='100m Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='hurdlesM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='110m Hürden Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='hurdlesW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='100m Hürden Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='javM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Speerwurf Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='javW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Speerwurf Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='longM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Weitsprung Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='longW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Weitsprung Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='poleVM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Stabhochsprung Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='poleVW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Stabhochsprung Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='shotM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Kugelstoß Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='shotW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Kugelstoß Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='steepleM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='3000m Hindernis Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='steepleW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='3000m Hindernis Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='tenKM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='10km Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='tenKW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='10km Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='tripleM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Dreisprung Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='tripleW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Dreisprung Frauen'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='twoM',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='200m Männer'),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='twoW',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='200m Frauen'),
        ),
    ]
